<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AppointmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        \App\Models\Appointment::create([
            'id'=>'111',
            'time'=>'10:00',
            'day'=>'sat',
			'hall'=>'a',
            'patient_status1' => '0',
			'patient_status2' => '0',
			'patient_status3' => '0',
			'patient_status4' => '0',
			'patient_status5' => '0',
            'doctor_status1'=>'1',
            'doctor_status2'=>'1',
            'doctor_status3'=>'1',
            'doctor_status4'=>'1',
            'doctor_status5'=>'1',
            'doctor_ssn'=>'8524001',
            ]);			
\App\Models\Appointment::create([
            'id'=>'112',
            'time'=>'10:00',
            'day'=>'sun',
			'hall'=>'a',
            'patient_status1' => '0',
			'patient_status2' => '0',
			'patient_status3' => '0',
			'patient_status4' => '0',
			'patient_status5' => '0',
            'doctor_status1'=>'1',
            'doctor_status2'=>'1',
            'doctor_status3'=>'1',
            'doctor_status4'=>'1',
            'doctor_status5'=>'1',
            'doctor_ssn'=>'8265003'
            ]);	
\App\Models\Appointment::create([
            'id'=>'113',
            'time'=>'10:00',
            'day'=>'mon',
			'hall'=>'a',
            'patient_status1' => '0',
			'patient_status2' => '0',
			'patient_status3' => '0',
			'patient_status4' => '0',
			'patient_status5' => '0',
            'doctor_status1'=>'1',
            'doctor_status2'=>'1',
            'doctor_status3'=>'1',
            'doctor_status4'=>'1',
            'doctor_status5'=>'1',
            'doctor_ssn'=>'8179005'
            ]);	
\App\Models\Appointment::create([
            'id'=>'114',
            'time'=>'10:00',
            'day'=>'tue',
			'hall'=>'a',
            'patient_status1' => '0',
			'patient_status2' => '0',
			'patient_status3' => '0',
			'patient_status4' => '0',
			'patient_status5' => '0',
            'doctor_status1'=>'1',
            'doctor_status2'=>'1',
            'doctor_status3'=>'1',
            'doctor_status4'=>'1',
            'doctor_status5'=>'1',

            ]);			
\App\Models\Appointment::create([
            'id'=>'115',
            'time'=>'10:00',
            'day'=>'wed',
			'hall'=>'a',
            'patient_status1' => '0',
			'patient_status2' => '0',
			'patient_status3' => '0',
			'patient_status4' => '0',
			'patient_status5' => '0',
            'doctor_status1'=>'1',
            'doctor_status2'=>'1',
            'doctor_status3'=>'1',
            'doctor_status4'=>'1',
            'doctor_status5'=>'1',
            'doctor_ssn'=>'8524001',
            ]);
\App\Models\Appointment::create([
            'id'=>'116',
            'time'=>'10:00',
            'day'=>'thu',
			'hall'=>'a',
            'patient_status1' => '0',
			'patient_status2' => '0',
			'patient_status3' => '0',
			'patient_status4' => '0',
			'patient_status5' => '0',
            'doctor_status1'=>'1',
            'doctor_status2'=>'1',
            'doctor_status3'=>'1',
            'doctor_status4'=>'1',
            'doctor_status5'=>'1',
            'doctor_ssn'=>'8265003'
            ]);			
\App\Models\Appointment::create([
            'id'=>'127',
            'time'=>'5:00',
            'day'=>'fri',
			'hall'=>'a',
            'patient_status1' => '0',
			'patient_status2' => '0',
			'patient_status3' => '0',
			'patient_status4' => '0',
			'patient_status5' => '0',
            'doctor_status1'=>'1',
            'doctor_status2'=>'1',
            'doctor_status3'=>'1',
            'doctor_status4'=>'1',
            'doctor_status5'=>'1',
            ]);			
\App\Models\Appointment::create([
            'id'=>'211',
            'time'=>'10:00',
            'day'=>'sat',
			'hall'=>'b',
            'patient_status1' => '0',
			'patient_status2' => '0',
			'patient_status3' => '0',
			'patient_status4' => '0',
			'patient_status5' => '0',
            'doctor_status1'=>'1',
            'doctor_status2'=>'1',
            'doctor_status3'=>'1',
            'doctor_status4'=>'1',
            'doctor_status5'=>'1',
            'doctor_ssn'=>'8354007'
            ]);			
\App\Models\Appointment::create([
            'id'=>'212',
            'time'=>'10:00',
            'day'=>'sun',
			'hall'=>'b',
            'patient_status1' => '0',
			'patient_status2' => '0',
			'patient_status3' => '0',
			'patient_status4' => '0',
			'patient_status5' => '0',
            'doctor_status1'=>'1',
            'doctor_status2'=>'1',
            'doctor_status3'=>'1',
            'doctor_status4'=>'1',
            'doctor_status5'=>'1',
            'doctor_ssn'=>'8775009'
            ]);	
\App\Models\Appointment::create([
            'id'=>'213',
            'time'=>'10:00',
            'day'=>'mon',
			'hall'=>'b',
            'patient_status1' => '0',
			'patient_status2' => '0',
			'patient_status3' => '0',
			'patient_status4' => '0',
			'patient_status5' => '0',
            'doctor_status1'=>'1',
            'doctor_status2'=>'1',
            'doctor_status3'=>'1',
            'doctor_status4'=>'1',
            'doctor_status5'=>'1',
            'doctor_ssn'=>'75890011'
            ]);	
\App\Models\Appointment::create([
            'id'=>'214',
            'time'=>'10:00',
            'day'=>'tue',
			'hall'=>'b',
            'patient_status1' => '0',
			'patient_status2' => '0',
			'patient_status3' => '0',
			'patient_status4' => '0',
			'patient_status5' => '0',
            'doctor_status1'=>'1',
            'doctor_status2'=>'1',
            'doctor_status3'=>'1',
            'doctor_status4'=>'1',
            'doctor_status5'=>'1',

            ]);			
\App\Models\Appointment::create([
            'id'=>'215',
            'time'=>'10:00',
            'day'=>'wed',
			'hall'=>'b',
            'patient_status1' => '0',
			'patient_status2' => '0',
			'patient_status3' => '0',
			'patient_status4' => '0',
			'patient_status5' => '0',
            'doctor_status1'=>'1',
            'doctor_status2'=>'1',
            'doctor_status3'=>'1',
            'doctor_status4'=>'1',
            'doctor_status5'=>'1',
            'doctor_ssn'=>'8354007'
            ]);
\App\Models\Appointment::create([
            'id'=>'216',
            'time'=>'10:00',
            'day'=>'thu',
			'hall'=>'b',
            'patient_status1' => '0',
			'patient_status2' => '0',
			'patient_status3' => '0',
			'patient_status4' => '0',
			'patient_status5' => '0',
            'doctor_status1'=>'1',
            'doctor_status2'=>'1',
            'doctor_status3'=>'1',
            'doctor_status4'=>'1',
            'doctor_status5'=>'1',
            'doctor_ssn'=>'8179005'
            ]);			
\App\Models\Appointment::create([
            'id'=>'227',
            'time'=>'05:00',
            'day'=>'fri',
			'hall'=>'b',
            'patient_status1' => '0',
			'patient_status2' => '0',
			'patient_status3' => '0',
			'patient_status4' => '0',
			'patient_status5' => '0',
            'doctor_status1'=>'1',
            'doctor_status2'=>'1',
            'doctor_status3'=>'1',
            'doctor_status4'=>'1',
            'doctor_status5'=>'1',
            ]);
\App\Models\Appointment::create([
            'id'=>'311',
            'time'=>'10:00',
            'day'=>'sat',
			'hall'=>'c',
            'patient_status1' => '0',
			'patient_status2' => '0',
			'patient_status3' => '0',
			'patient_status4' => '0',
			'patient_status5' => '0',
            'doctor_status1'=>'1',
            'doctor_status2'=>'1',
            'doctor_status3'=>'1',
            'doctor_status4'=>'1',
            'doctor_status5'=>'1',
            'doctor_ssn'=>'88811013'
            ]);			
\App\Models\Appointment::create([
            'id'=>'312',
            'time'=>'10:00',
            'day'=>'sun',
			'hall'=>'c',
            'patient_status1' => '0',
			'patient_status2' => '0',
			'patient_status3' => '0',
			'patient_status4' => '0',
			'patient_status5' => '0',
            'doctor_status1'=>'1',
            'doctor_status2'=>'1',
            'doctor_status3'=>'1',
            'doctor_status4'=>'1',
            'doctor_status5'=>'1',
            'doctor_ssn'=>'91189015'
            ]);	
\App\Models\Appointment::create([
            'id'=>'313',
            'time'=>'10:00',
            'day'=>'mon',
			'hall'=>'c',
            'patient_status1' => '0',
			'patient_status2' => '0',
			'patient_status3' => '0',
			'patient_status4' => '0',
			'patient_status5' => '0',
            'doctor_status1'=>'1',
            'doctor_status2'=>'1',
            'doctor_status3'=>'1',
            'doctor_status4'=>'1',
            'doctor_status5'=>'1',
            ]);	
\App\Models\Appointment::create([
            'id'=>'314',
            'time'=>'10:00',
            'day'=>'tue',
			'hall'=>'c',
            'patient_status1' => '0',
			'patient_status2' => '0',
			'patient_status3' => '0',
			'patient_status4' => '0',
			'patient_status5' => '0',
            'doctor_status1'=>'1',
            'doctor_status2'=>'1',
            'doctor_status3'=>'1',
            'doctor_status4'=>'1',
            'doctor_status5'=>'1',
            ]);			
\App\Models\Appointment::create([
            'id'=>'315',
            'time'=>'10:00',
            'day'=>'wed',
			'hall'=>'c',
            'patient_status1' => '0',
			'patient_status2' => '0',
			'patient_status3' => '0',
			'patient_status4' => '0',
			'patient_status5' => '0',
            'doctor_status1'=>'1',
            'doctor_status2'=>'1',
            'doctor_status3'=>'1',
            'doctor_status4'=>'1',
            'doctor_status5'=>'1',
            'doctor_ssn'=>'88811013'
            ]);
\App\Models\Appointment::create([
            'id'=>'316',
            'time'=>'10:00',
            'day'=>'thu',
			'hall'=>'c',
            'patient_status1' => '0',
			'patient_status2' => '0',
			'patient_status3' => '0',
			'patient_status4' => '0',
			'patient_status5' => '0',
            'doctor_status1'=>'1',
            'doctor_status2'=>'1',
            'doctor_status3'=>'1',
            'doctor_status4'=>'1',
            'doctor_status5'=>'1',
            'doctor_ssn'=>'91189015'
            ]);			
\App\Models\Appointment::create([
            'id'=>'327',
            'time'=>'05:00',
            'day'=>'fri',
			'hall'=>'c',
            'patient_status1' => '0',
			'patient_status2' => '0',
			'patient_status3' => '0',
			'patient_status4' => '0',
			'patient_status5' => '0',
            'doctor_status1'=>'1',
            'doctor_status2'=>'1',
            'doctor_status3'=>'1',
            'doctor_status4'=>'1',
            'doctor_status5'=>'1',
            'doctor_ssn'=>'75890011'

            ]);
\App\Models\Appointment::create([
            'id'=>'121',
            'time'=>'05:00',
            'day'=>'sat',
			'hall'=>'a',
            'patient_status1' => '0',
			'patient_status2' => '0',
			'patient_status3' => '0',
			'patient_status4' => '0',
			'patient_status5' => '0',
            'doctor_status1'=>'1',
            'doctor_status2'=>'1',
            'doctor_status3'=>'1',
            'doctor_status4'=>'1',
            'doctor_status5'=>'1',
			'doctor_ssn'=>'8542002'
            ]);			
\App\Models\Appointment::create([
            'id'=>'122',
            'time'=>'05:00',
            'day'=>'sun',
			'hall'=>'a',
            'patient_status1' => '0',
			'patient_status2' => '0',
			'patient_status3' => '0',
			'patient_status4' => '0',
			'patient_status5' => '0',
            'doctor_status1'=>'1',
            'doctor_status2'=>'1',
            'doctor_status3'=>'1',
            'doctor_status4'=>'1',
            'doctor_status5'=>'1',
			'doctor_ssn'=>'8256004'
            ]);	
\App\Models\Appointment::create([
            'id'=>'123',
            'time'=>'05:00',
            'day'=>'mon',
			'hall'=>'a',
            'patient_status1' => '0',
			'patient_status2' => '0',
			'patient_status3' => '0',
			'patient_status4' => '0',
			'patient_status5' => '0',
            'doctor_status1'=>'1',
            'doctor_status2'=>'1',
            'doctor_status3'=>'1',
            'doctor_status4'=>'1',
            'doctor_status5'=>'1',
			'doctor_ssn'=>'8197006'
            ]);	
\App\Models\Appointment::create([
            'id'=>'124',
            'time'=>'05:00',
            'day'=>'tue',
			'hall'=>'a',
            'patient_status1' => '0',
			'patient_status2' => '0',
			'patient_status3' => '0',
			'patient_status4' => '0',
			'patient_status5' => '0',
            'doctor_status1'=>'1',
            'doctor_status2'=>'1',
            'doctor_status3'=>'1',
            'doctor_status4'=>'1',
            'doctor_status5'=>'1',
			
            ]);			
\App\Models\Appointment::create([
            'id'=>'125',
            'time'=>'05:00',
            'day'=>'wed',
			'hall'=>'a',
            'patient_status1' => '0',
			'patient_status2' => '0',
			'patient_status3' => '0',
			'patient_status4' => '0',
			'patient_status5' => '0',
            'doctor_status1'=>'1',
            'doctor_status2'=>'1',
            'doctor_status3'=>'1',
            'doctor_status4'=>'1',
            'doctor_status5'=>'1',
			'doctor_ssn'=>'8542002'
            ]);
\App\Models\Appointment::create([
            'id'=>'126',
            'time'=>'05:00',
            'day'=>'thu',
			'hall'=>'a',
            'patient_status1' => '0',
			'patient_status2' => '0',
			'patient_status3' => '0',
			'patient_status4' => '0',
			'patient_status5' => '0',
            'doctor_status1'=>'1',
            'doctor_status2'=>'1',
            'doctor_status3'=>'1',
            'doctor_status4'=>'1',
            'doctor_status5'=>'1',
			'doctor_ssn'=>'8256004'
            ]);				
\App\Models\Appointment::create([
            'id'=>'221',
            'time'=>'05:00',
            'day'=>'sat',
			'hall'=>'b',
            'patient_status1' => '0',
			'patient_status2' => '0',
			'patient_status3' => '0',
			'patient_status4' => '0',
			'patient_status5' => '0',
            'doctor_status1'=>'1',
            'doctor_status2'=>'1',
            'doctor_status3'=>'1',
            'doctor_status4'=>'1',
            'doctor_status5'=>'1',
			'doctor_ssn'=>'8345008'
            ]);			
\App\Models\Appointment::create([
            'id'=>'222',
            'time'=>'05:00',
            'day'=>'sun',
			'hall'=>'b',
            'patient_status1' => '0',
			'patient_status2' => '0',
			'patient_status3' => '0',
			'patient_status4' => '0',
			'patient_status5' => '0',
            'doctor_status1'=>'1',
            'doctor_status2'=>'1',
            'doctor_status3'=>'1',
            'doctor_status4'=>'1',
            'doctor_status5'=>'1',
			'doctor_ssn'=>'87570010'
            ]);	
\App\Models\Appointment::create([
            'id'=>'223',
            'time'=>'05:00',
            'day'=>'mon',
			'hall'=>'b',
            'patient_status1' => '0',
			'patient_status2' => '0',
			'patient_status3' => '0',
			'patient_status4' => '0',
			'patient_status5' => '0',
            'doctor_status1'=>'1',
            'doctor_status2'=>'1',
            'doctor_status3'=>'1',
            'doctor_status4'=>'1',
            'doctor_status5'=>'1',
			'doctor_ssn'=>'75980012'
            ]);	
\App\Models\Appointment::create([
            'id'=>'224',
            'time'=>'05:00',
            'day'=>'tue',
			'hall'=>'b',
            'patient_status1' => '0',
			'patient_status2' => '0',
			'patient_status3' => '0',
			'patient_status4' => '0',
			'patient_status5' => '0',
            'doctor_status1'=>'1',
            'doctor_status2'=>'1',
            'doctor_status3'=>'1',
            'doctor_status4'=>'1',
            'doctor_status5'=>'1',
			
            ]);			
\App\Models\Appointment::create([
            'id'=>'225',
            'time'=>'05:00',
            'day'=>'wed',
			'hall'=>'b',
            'patient_status1' => '0',
			'patient_status2' => '0',
			'patient_status3' => '0',
			'patient_status4' => '0',
			'patient_status5' => '0',
            'doctor_status1'=>'1',
            'doctor_status2'=>'1',
            'doctor_status3'=>'1',
            'doctor_status4'=>'1',
            'doctor_status5'=>'1',
			'doctor_ssn'=>'8345008'
            ]);
\App\Models\Appointment::create([
            'id'=>'226',
            'time'=>'05:00',
            'day'=>'thu',
			'hall'=>'b',
            'patient_status1' => '0',
			'patient_status2' => '0',
			'patient_status3' => '0',
			'patient_status4' => '0',
			'patient_status5' => '0',
            'doctor_status1'=>'1',
            'doctor_status2'=>'1',
            'doctor_status3'=>'1',
            'doctor_status4'=>'1',
            'doctor_status5'=>'1',
			'doctor_ssn'=>'87570010'
            ]);			
\App\Models\Appointment::create([
            'id'=>'321',
            'time'=>'05:00',
            'day'=>'sat',
			'hall'=>'c',
            'patient_status1' => '0',
			'patient_status2' => '0',
			'patient_status3' => '0',
			'patient_status4' => '0',
			'patient_status5' => '0',
            'doctor_status1'=>'1',
            'doctor_status2'=>'1',
            'doctor_status3'=>'1',
            'doctor_status4'=>'1',
            'doctor_status5'=>'1',
			'doctor_ssn'=>'88118014'
            ]);			
\App\Models\Appointment::create([
            'id'=>'322',
            'time'=>'05:00',
            'day'=>'sun',
			'hall'=>'c',
            'patient_status1' => '0',
			'patient_status2' => '0',
			'patient_status3' => '0',
			'patient_status4' => '0',
			'patient_status5' => '0',
            'doctor_status1'=>'1',
            'doctor_status2'=>'1',
            'doctor_status3'=>'1',
            'doctor_status4'=>'1',
            'doctor_status5'=>'1',
			'doctor_ssn'=>'84189016'
            ]);	
\App\Models\Appointment::create([
            'id'=>'323',
            'time'=>'05:00',
            'day'=>'mon',
			'hall'=>'c',
            'patient_status1' => '0',
			'patient_status2' => '0',
			'patient_status3' => '0',
			'patient_status4' => '0',
			'patient_status5' => '0',
            'doctor_status1'=>'1',
            'doctor_status2'=>'1',
            'doctor_status3'=>'1',
            'doctor_status4'=>'1',
            'doctor_status5'=>'1',
			'doctor_ssn'=>'8775009'
            ]);	
\App\Models\Appointment::create([
            'id'=>'324',
            'time'=>'05:00',
            'day'=>'tue',
			'hall'=>'c',
            'patient_status1' => '0',
			'patient_status2' => '0',
			'patient_status3' => '0',
			'patient_status4' => '0',
			'patient_status5' => '0',
            'doctor_status1'=>'1',
            'doctor_status2'=>'1',
            'doctor_status3'=>'1',
            'doctor_status4'=>'1',
            'doctor_status5'=>'1',
            ]);			
\App\Models\Appointment::create([
            'id'=>'325',
            'time'=>'05:00',
            'day'=>'wed',
			'hall'=>'c',
            'patient_status1' => '0',
			'patient_status2' => '0',
			'patient_status3' => '0',
			'patient_status4' => '0',
			'patient_status5' => '0',
            'doctor_status1'=>'1',
            'doctor_status2'=>'1',
            'doctor_status3'=>'1',
            'doctor_status4'=>'1',
            'doctor_status5'=>'1',
			'doctor_ssn'=>'88118014'
            ]);
\App\Models\Appointment::create([
            'id'=>'326',
            'time'=>'05:00',
            'day'=>'thu',
			'hall'=>'c',
            'patient_status1' => '0',
			'patient_status2' => '0',
			'patient_status3' => '0',
			'patient_status4' => '0',
			'patient_status5' => '0',
            'doctor_status1'=>'1',
            'doctor_status2'=>'1',
            'doctor_status3'=>'1',
            'doctor_status4'=>'1',
            'doctor_status5'=>'1',
			'doctor_ssn'=>'84189016'
            ]);

    }
}
